install.packages("tidyverse")
install.packages("readxl")
install.packages("dslabs")
install.packages("ggrepel")
install.packages("rvest")
install.packages("purrr")
install.packages("pdftools")

install.packages("stringr")
install.packages("lubridate")
install.packages("ggplot2")
install.packages("scales")
install.packages("tidytext")
install.packages("broom")
install.packages("gutenbergr")
install.packages("")
install.packages("")
install.packages("")